feature_columns_plr = [
    'valid count in white pictures',

    'mean of maximum pupil amplitude in white pictures',
    'mean of minimum pupil amplitude in white pictures',
    'mean of the time when the maximum pupil amplitude appears in white pictures',
    'mean of the time when the minimum pupil amplitude appears in white pictures',
    'mean of pupil constriction amplitude in white pictures',
    'mean of pupil constriction time in white pictures',
    'mean of average pupil constriction velocity in white pictures',

    'standard deviation of maximum pupil amplitude in white pictures',
    'standard deviation of minimum pupil amplitude in white pictures',
    'standard deviation of the time when the maximum pupil amplitude appears in white pictures',
    'standard deviation of the time when the minimum pupil amplitude appears in white pictures',
    'standard deviation of pupil constriction amplitude in white pictures',
    'standard deviation of pupil constriction time in white pictures',
    'standard deviation of average pupil constriction velocity in white pictures',

    'minimum of maximum pupil amplitude in white pictures',
    'minimum of minimum pupil amplitude in white pictures',
    'minimum of the time when the maximum pupil amplitude appears in white pictures',
    'minimum of the time when the minimum pupil amplitude appears in white pictures',
    'minimum of pupil constriction amplitude in white pictures',
    'minimum of pupil constriction time in white pictures',
    'minimum of average pupil constriction velocity in white pictures',

    'middle of maximum pupil amplitude in white pictures',
    'middle of minimum pupil amplitude in white pictures',
    'middle of the time when the maximum pupil amplitude appears in white pictures',
    'middle of the time when the minimum pupil amplitude appears in white pictures',
    'middle of pupil constriction amplitude in white pictures',
    'middle of pupil constriction time in white pictures',
    'middle of average pupil constriction velocity in white pictures',

    'maximum of maximum pupil amplitude in white pictures',
    'maximum of minimum pupil amplitude in white pictures',
    'maximum of the time when the maximum pupil amplitude appears in white pictures',
    'maximum of the time when the minimum pupil amplitude appears in white pictures',
    'maximum of pupil constriction amplitude in white pictures',
    'maximum of pupil constriction time in white pictures',
    'maximum of average pupil constriction velocity in white pictures',

    'valid count in black pictures',

    'mean of maximum pupil amplitude in black pictures',
    'mean of minimum pupil amplitude in black pictures',
    'mean of the time when the maximum pupil amplitude appears in black pictures',
    'mean of the time when the minimum pupil amplitude appears in black pictures',
    'mean of pupil dilation amplitude in black pictures',
    'mean of pupil dilation time in black pictures',
    'mean of average pupil dilation velocity in black pictures',

    'standard deviation of maximum pupil amplitude in black pictures',
    'standard deviation of minimum pupil amplitude in black pictures',
    'standard deviation of the time when the maximum pupil amplitude appears in black pictures',
    'standard deviation of the time when the minimum pupil amplitude appears in black pictures',
    'standard deviation of pupil dilation amplitude in black pictures',
    'standard deviation of pupil dilation time in black pictures',
    'standard deviation of average pupil dilation velocity in black pictures',

    'minimum of maximum pupil amplitude in black pictures',
    'minimum of minimum pupil amplitude in black pictures',
    'minimum of the time when the maximum pupil amplitude appears in black pictures',
    'minimum of the time when the minimum pupil amplitude appears in black pictures',
    'minimum of pupil dilation amplitude in black pictures',
    'minimum of pupil dilation time in black pictures',
    'minimum of average pupil dilation velocity in black pictures',

    'middle of maximum pupil amplitude in black pictures',
    'middle of minimum pupil amplitude in black pictures',
    'middle of the time when the maximum pupil amplitude appears in black pictures',
    'middle of the time when the minimum pupil amplitude appears in black pictures',
    'middle of pupil dilation amplitude in black pictures',
    'middle of pupil dilation time in black pictures',
    'middle of average pupil dilation velocity in black pictures',

    'maximum of maximum pupil amplitude in black pictures',
    'maximum of minimum pupil amplitude in black pictures',
    'maximum of the time when the maximum pupil amplitude appears in black pictures',
    'maximum of the time when the minimum pupil amplitude appears in black pictures',
    'maximum of pupil dilation amplitude in black pictures',
    'maximum of pupil dilation time in black pictures',
    'maximum of average pupil dilation velocity in black pictures',

    'baseline pupil diameter',

    'name',
    'label'
]